# Generated by Django 3.2.5 on 2025-05-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reator',
            new_name='creator',
        ),
    ]
